# Commands to start on workspace startup
tasks:
  - init: ./webodm.sh start --setup-devenv
    # command: yarn build
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview